pull request
Nooria150/personal_portfolio_webpage1 pull request #1
Opened 2024-05-30 20:28 UTC by Nooria150

1. At first cloned my repo.
2. I followed the Gitlow.
3. created feature branch.
4. setup linters.
5. added readme.md file.
6. started coding for my portfolio website.
7. then I designed it.

2024-06-04 14:05 UTC, ahzamir requested changes
### Hi @Nooria150 🙋‍♀️,

> Excellent work! You have done a great job implementing the project requirements but your project still misses some of the requirements:

- Although you have passed the project requirement, but your code is not clean and also your portfolio links are all directed to the github, give the exact links for all of them.

# Status: Required Changes 🔁
Make changes to your code and commit and request for a re-review.

![AlmostThereReachGIF](https://github.com/LimaSahibzada/Survey-Form-project1/assets/96838030/4f0a3cd6-3a46-4e1e-8e31-ef617d4e8ac3)

 ## Highlights 🌞
 
🎯 Great Design implemented.
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed and completed the Personal Portfolio and all requirements.
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
❌Your code is clean
✔️Your project has a professional README.md file

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me @ahzamir in your question so I can receive the notification.**

2024-06-05 20:09 UTC, Nooria150 commented
thank you so mush sir for the review. I Implemented the feedback. I check it from every view It is correct, my partner is not  capable to check my website. so that's why I wanna tag you again. @ahzamir

2024-06-05 20:18 UTC, ahzamir commented
@Nooria150 

- You have to tag her for review and feedback if she is capable or not doesn't matter and also remind her in the group to provide you review and feedback.

- If she did not provide you feedback within 24 hours then you can ask me to provide you feedback.
  - But don't forget that you have to request me after you implemented the best version of your code it means you were sure and checked everything.

2024-06-05 20:34 UTC, Nooria150 commented
@ahzamir 
sure sir! can I tag her they same way I tagged you? I mean her email address name?

2024-06-05 20:39 UTC, Nooria150 commented
@ahzamir 
sorry! I think I should tag her github name.

2024-06-06 08:48 UTC, Breshnahamidi20 commented
Hi@Nooria150
I want to review your code and clone it to my local machine, but there is something wrong with the link.

2024-06-06 16:05 UTC, ahzamir commented
@Breshnahamidi20 

- You have to use her ssh project link inorder to clone her project and check.

2024-06-06 19:49 UTC, Nooria150 commented
@ahzamir please check my project. coz tomorrow is deadline. And tomorrow is my brother's wedding. I have tried my best to  make it the best project but when I saw some of girls project I think mine is not enough good. sorry for disappointed you. 
I think I still have to learning more about CSS. this would not be enough for making good website.

2024-06-06 19:55 UTC, ahzamir requested changes

2024-06-06 19:55 UTC, ahzamir commented on index.html
> +</footer>
- These codes all are inside your body si they all should be 2 spaces ahead of your body tag

2024-06-07 04:02 UTC, Nooria150 commented
@ahzamir I implemented the feedback.

2024-06-07 18:22 UTC, ahzamir approved these changes
### Hi @Nooria150 🙋‍♀️,

> Excellent work! 💯 You have done a great job implementing all the project requirements. 🥳 Your feature is complete! Congratulations!!!🎊

- **[REQUIRED]** Share your project on this [GROUP](https://www.facebook.com/groups/kick-startdev), add a simple Proud Moment text and a screenshot of your project then besides that add your project link at the end of the text as a GitHub Source code reference and post.

- Share your Project on your LinkedIn account and add a proud moment text on it with a screenshot.

- Well Done great design Implemented. 🎯🎉👍

# Status: Approved ✅
There is nothing to say other than to merge your branch. 🎉🎯✅👍😊🥳

![GreatJobThumbsUpGIF](https://github.com/ZuhRa-HashiMi/survey-form/assets/96838030/cc459d3f-5796-43f0-aba7-4ed0c35fa276)

 ## Highlights 🌞

🎉 Great Design Implemented 
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed the Personal Portfolio project task and committed using the command line
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
✔️Your code is clean
✔️Your project has a professional README.md file.

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me @ahzamir in your question so I can receive the notification.**

2024-06-14 19:11 UTC, merged